### ISSUE TITLE
Please publish to PyPI

### ISSUE THREAD

**Issue by mgood** [papaeye/pytest-httpretty#1]
I've found this package really useful, but I don't see it on PyPI.  For now I've just been putting it in my test requirements using the Github URL, but it would be nice to have an official release.

Would you be willing publish it?

**Comment by papaeye** [comment]
@mgood Sorry for the late relay.  Now I uploaded this. 
Note that fixtures were switched to a marker and a shorthand function.

**Comment by mgood** [comment]
Thanks, I'll make sure I use that when I update.
